server:
  port: 8088 
  servlet:
    path: /myboot
    
# MVC 
spring:
  mvc:
    view:
      prefix: /  
      suffix: .jsp 
    
#spring:
  #datasource:
    #url: jdbc:mysql:///mydb
    #username: root  
    #password: root
    
  #mvc:
    #static-path-pattern: /**
  #resources:
    #static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/